# Generated by Django 4.1.1 on 2022-11-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Admin", "0002_registration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="role",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.DeleteModel(name="Role",),
    ]
