# Generated by Django 4.1.2 on 2022-11-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_alter_registration_role_delete_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='user_status',
            field=models.IntegerField(default='1'),
        ),
    ]
