# Generated by Django 4.1.1 on 2022-11-01 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turfregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turf_name', models.CharField(max_length=100)),
                ('turf_phone', models.CharField(max_length=12)),
                ('turf_desc', models.CharField(default='', max_length=50)),
                ('turf_img', models.ImageField(upload_to='images')),
                ('turf_rate', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teamuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_phone', models.CharField(max_length=12)),
                ('user_email', models.CharField(default='', max_length=20)),
                ('user_pass', models.CharField(max_length=50)),
                ('user_location', models.CharField(default='', max_length=50)),
                ('user_status', models.IntegerField()),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.role')),
            ],
        ),
    ]
