# Generated by Django 4.1.1 on 2022-11-01 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Turfregistration',
        ),
    ]
