# Generated by Django 4.1.1 on 2022-11-01 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
        ('Team', '0002_delete_turfregistration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teamuser',
            new_name='Registration',
        ),
    ]
