# Generated by Django 4.1.1 on 2022-11-11 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Team", "0003_rename_teamuser_registration"),
    ]

    operations = [
        migrations.RemoveField(model_name="registration", name="user_location",),
    ]
