# Generated by Django 4.1.1 on 2022-11-11 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Team", "0004_remove_registration_user_location"),
    ]

    operations = [
        migrations.DeleteModel(name="Registration",),
    ]
