# Generated by Django 4.1.1 on 2022-12-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Team', '0005_delete_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament_Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='', max_length=100)),
                ('tid', models.CharField(max_length=100)),
            ],
        ),
    ]
