# Generated by Django 4.1.1 on 2022-12-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0006_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament_booking',
            name='turf_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
