# Generated by Django 4.1.1 on 2022-12-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0007_tournament_booking_turf_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament_booking',
            name='Tournament_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tournament_booking',
            name='user_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
