# Generated by Django 4.1.1 on 2022-12-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0009_turf_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf_booking',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
