# Generated by Django 4.1.1 on 2022-12-20 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0010_turf_booking_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turf_booking',
            name='tid',
        ),
    ]
