# Generated by Django 4.1.1 on 2022-12-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0012_alter_turf_booking_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf_booking',
            name='date',
            field=models.CharField(default='', max_length=100),
        ),
    ]
