# Generated by Django 4.1.1 on 2022-12-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0013_turf_booking_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='', max_length=100)),
                ('user_name', models.CharField(default='', max_length=100)),
                ('Turf_name', models.CharField(default='', max_length=100)),
                ('turf_id', models.CharField(default='', max_length=100)),
                ('star', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
