# Generated by Django 4.1.1 on 2022-11-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turfregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turf_name', models.CharField(max_length=100)),
                ('turf_phone', models.CharField(max_length=12)),
                ('turf_desc', models.CharField(default='', max_length=50)),
                ('turf_img', models.ImageField(upload_to='images')),
                ('turf_rate', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
