# Generated by Django 4.1.1 on 2022-11-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turfregistration',
            name='turf_address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='turfregistration',
            name='turf_feature',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='turfregistration',
            name='turf_location',
            field=models.CharField(default='', max_length=50),
        ),
    ]
