# Generated by Django 4.1.1 on 2022-11-26 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organizer', '0002_turfregistration_turf_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turfregistration',
            name='turf_phone',
        ),
    ]
