# Generated by Django 4.1.1 on 2022-12-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizer', '0003_remove_turfregistration_turf_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turfregistration',
            name='turf_feature',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
