# Generated by Django 4.1.1 on 2022-12-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizer', '0007_alter_turfregistration_turf_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turfregistration',
            name='turf_img',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
