# Generated by Django 4.1.1 on 2022-12-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizer', '0008_alter_turfregistration_turf_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host_Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tournament_name', models.CharField(max_length=100)),
                ('Tournament_date', models.CharField(default='', max_length=20)),
                ('Tournament_rate', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='turfregistration',
            name='uid',
            field=models.CharField(default='', max_length=100),
        ),
    ]
