# Generated by Django 4.1.1 on 2022-12-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizer', '0010_alter_host_tournament_tournament_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='host_tournament',
            name='Tournament_desc',
            field=models.CharField(default='', max_length=150),
        ),
    ]
