# Generated by Django 4.1.1 on 2022-12-13 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organizer', '0012_host_tournament_tournament_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host_tournament',
            old_name='Tournament_id',
            new_name='uid',
        ),
    ]
