# Generated by Django 4.1.1 on 2022-12-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizer', '0013_rename_tournament_id_host_tournament_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host_tournament',
            name='Tournament_desc',
            field=models.CharField(default='', max_length=750),
        ),
        migrations.AlterField(
            model_name='turfregistration',
            name='turf_desc',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
