# Generated by Django 4.1.1 on 2022-12-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizer', '0015_turfregistration_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='host_tournament',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
